spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/primes_db
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
